import Background from "@/components/ui/background";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Etudify",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<link
				href="https://framerusercontent.com/images/6DtbRJUy8Iav5zS4Ls95q1lxtM.png"
				rel="icon"
				media="(prefers-color-scheme: light)"
			/>
			<link
				href="https://framerusercontent.com/images/RB1vserSxuglsTZE2CKyruOiK88.png"
				rel="icon"
				media="(prefers-color-scheme: dark)"
			/>
			<link
				rel="apple-touch-icon"
				href="https://framerusercontent.com/images/kEN8Z3RmSIaUolb0SFQR5nLtDc.png"></link>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				    {children}
				<Toaster />
				<Background />
			</body>
		</html>
	);
}
